import { useEffect, useState } from "react";
import { AlertTriangle, Box, Bug, Cable, ChevronRight, FileDown, FileUp, Gauge, Network, Radio, RefreshCcw, Router, TerminalSquare } from "lucide-react";
import { addForward, blackboxBlame, blackboxes, listForwards, removeForward, setBlackbox, topSnapshot, transfer, workflowExecute, workflowPreview } from "./bridge";
import type { BlackboxView, ForwardView, TopRow, WorkflowPlan } from "./types";

interface Props { device: string; onActivity: (message: string) => void; onOpenTask: (title: string, command: string) => void; }
const logCommand = "if command -v journalctl >/dev/null 2>&1; then journalctl -f -n 100; elif [ -f /var/log/messages ]; then tail -n 100 -F /var/log/messages; else dmesg -w; fi";

export function OperationsPanel({ device, onActivity, onOpenTask }: Props) {
  const [local, setLocal] = useState(""); const [remote, setRemote] = useState("/tmp/"); const [direction, setDirection] = useState<"push" | "pull">("push");
  const [taskCommand, setTaskCommand] = useState("./app");
  const [forwards, setForwards] = useState<ForwardView[]>([]); const [spec, setSpec] = useState("8080:80"); const [top, setTop] = useState<TopRow[]>([]);
  const [boxes, setBoxes] = useState<BlackboxView[]>([]); const [blame, setBlame] = useState(""); const [workflow, setWorkflow] = useState<WorkflowPlan>();
  const [kind, setKind] = useState("share"); const [nat, setNat] = useState(false); const [persist, setPersist] = useState(false); const [bootOk, setBootOk] = useState(false); const [mode, setMode] = useState("ncm"); const [busy, setBusy] = useState(false);
  const refresh = async () => { const [f, t, b] = await Promise.all([listForwards(), topSnapshot(), blackboxes()]); setForwards(f); setTop(t); setBoxes(b); };
  useEffect(() => { void refresh().catch((error) => onActivity(`Operations refresh failed: ${String(error)}`)); }, [device]);
  const run = async (label: string, operation: () => Promise<{ detail: string }>) => { setBusy(true); try { const result = await operation(); onActivity(`${label}: ${result.detail}`); await refresh(); } catch (error) { onActivity(`${label} failed: ${String(error)}`); } finally { setBusy(false); } };
  const preview = async () => { try { setWorkflow(await workflowPreview(kind, device, nat, persist, bootOk, mode)); } catch (error) { onActivity(`Workflow preflight failed: ${String(error)}`); } };
  const execute = () => run(`${kind} workflow`, () => workflowExecute({ kind, device, nat, persist, bootOk, mode, confirmed: true }));

  return <section className="operations-panel">
    <header className="operations-header"><div><strong>Operations</strong><span>P2 workbench and P3 guarded workflows</span></div><button className="icon-button" title="Refresh operations" onClick={() => void refresh()}><RefreshCcw size={16} /></button></header>
    <div className="operations-scroll">
      <section className="operation-section"><h2><FileUp size={15} /> File transfer</h2><div className="segmented"><button className={direction === "push" ? "selected" : ""} onClick={() => setDirection("push")}>Push</button><button className={direction === "pull" ? "selected" : ""} onClick={() => setDirection("pull")}>Pull</button></div><label>Local path<input value={local} onChange={(event) => setLocal(event.target.value)} placeholder="/path/to/artifact" /></label><label>Remote path<input value={remote} onChange={(event) => setRemote(event.target.value)} placeholder="/tmp/" /></label><button className="operation-button" disabled={!device || !local || !remote || busy} onClick={() => void run(direction, () => transfer({ name: device, direction, local, remote, force: false, resume: true, verify: true }))}>{direction === "push" ? <FileUp size={15} /> : <FileDown size={15} />}{direction === "push" ? "Transfer to device" : "Retrieve from device"}</button></section>

      <section className="operation-section"><h2><TerminalSquare size={15} /> Run and logs</h2><label>Remote command<input value={taskCommand} onChange={(event) => setTaskCommand(event.target.value)} placeholder="/tmp/app --verbose" /></label><div className="inline-actions"><button onClick={() => onOpenTask("Run", taskCommand)} disabled={!device || !taskCommand}><TerminalSquare size={14} />Run</button><button onClick={() => onOpenTask("Logs", logCommand)} disabled={!device}><Radio size={14} />Follow logs</button><button onClick={() => onOpenTask("Debug", `gdbserver :2345 ${taskCommand}`)} disabled={!device || !taskCommand}><Bug size={14} />Debug</button></div><p className="operation-note">Run/debug and log follow open in an xterm tab, preserving interactive output and Ctrl-C.</p></section>

      <section className="operation-section"><h2><Router size={15} /> Port forwards</h2><div className="inline-form"><input value={spec} onChange={(event) => setSpec(event.target.value)} aria-label="Forward rule" /><button title="Add forward" disabled={!device || !spec || busy} onClick={() => void run("Forward", () => addForward(device, spec))}><ChevronRight size={16} /></button></div>{forwards.length ? forwards.map((forward) => <div className="operation-row" key={`${forward.channel}-${forward.id}-${forward.detail}`}><span className={`status-dot ${forward.alive ? "online" : "offline"}`} /><span>{forward.device}: {forward.detail}</span>{forward.id !== "-" && <button title="Remove forward" onClick={() => void run("Forward", () => removeForward(forward.id))}>x</button>}</div>) : <p className="operation-note">No active forwards.</p>}</section>

      <section className="operation-section"><h2><Gauge size={15} /> Device top</h2><div className="top-grid">{top.map((row) => <div className="top-row" key={row.name}><strong><span className={`status-dot ${row.online ? "online" : "offline"}`} />{row.name}</strong><span>CPU {row.cpu} · MEM {row.memory}</span><span>{row.temperature} · load {row.load}</span></div>)}</div></section>

      <section className="operation-section"><h2><Box size={15} /> Serial black box</h2>{boxes.map((box) => <div className="blackbox-row" key={box.name}><div><strong>{box.name}</strong><span>{box.incidents} incident(s)</span></div><button onClick={() => void run("Black box", () => setBlackbox(box.name, !box.running))}>{box.running ? "Stop" : "Start"}</button><button title="Show latest incident" onClick={() => void blackboxBlame(box.name).then(setBlame).catch((error) => onActivity(`Blame failed: ${String(error)}`))}>Blame</button></div>)}{blame && <pre className="blame-output">{blame}</pre>}</section>

      <section className="operation-section guarded"><h2><AlertTriangle size={15} /> Guided recovery and networking</h2><label>Workflow<select value={kind} onChange={(event) => setKind(event.target.value)}><option value="share">Share host network</option><option value="up">Promote serial to SSH</option><option value="usb-net">Configure USB network</option><option value="gadget-install">Install USB gadget</option></select></label><div className="check-grid"><label><input type="checkbox" checked={nat} onChange={(event) => setNat(event.target.checked)} />Use NAT / host sharing</label><label><input type="checkbox" checked={persist} onChange={(event) => setPersist(event.target.checked)} />Persist or autostart</label>{kind === "up" && <label><input type="checkbox" checked={bootOk} onChange={(event) => setBootOk(event.target.checked)} />Allow bootloader boot</label>}</div>{kind === "gadget-install" && <label>Gadget mode<select value={mode} onChange={(event) => setMode(event.target.value)}><option value="ncm">NCM</option><option value="rndis">RNDIS</option></select></label>}<button className="operation-button preview" disabled={!device || busy} onClick={() => void preview()}><Network size={15} />Preflight and dry-run plan</button>{workflow && <div className="workflow-plan"><strong className={workflow.preflightOk ? "ok" : "warn"}>{workflow.preflight}</strong>{workflow.steps.map((step) => <p key={step}>{step}</p>)}<p><b>Rollback:</b> {workflow.rollback}</p><button className="operation-button danger" disabled={!workflow.preflightOk || busy} onClick={() => void execute()}><Cable size={15} />I reviewed the plan, execute</button></div>}</section>
    </div>
  </section>;
}
