import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Download, FolderPlus, LoaderCircle, PackagePlus, RefreshCcw, ShieldCheck } from "lucide-react";
import { installPlugin, listPlugins, pluginPreview, runPlugin } from "./bridge";
import type { PluginPlan, PluginView } from "./types";

interface Props { device: string; transport: string; hasPassword: boolean; active: boolean; onActivity: (message: string) => void; }

export function PluginsPanel({ device, transport, hasPassword, active, onActivity }: Props) {
  const [plugins, setPlugins] = useState<PluginView[]>([]); const [destination, setDestination] = useState(""); const [useSudo, setUseSudo] = useState(false); const [deleteStale, setDeleteStale] = useState(false);
  const [packagePath, setPackagePath] = useState(""); const [plan, setPlan] = useState<PluginPlan>(); const [output, setOutput] = useState(""); const [busy, setBusy] = useState(false);
  const sysroot = useMemo(() => plugins.find((plugin) => plugin.id === "sysroot-sync"), [plugins]);
  const sysrootArgs = useMemo(() => ["--dest", destination || `~/ferry-sysroots/${device || "target"}`, ...(useSudo ? [] : ["--no-sudo"]), ...(deleteStale ? ["--delete"] : [])], [deleteStale, destination, device, useSudo]);
  const refresh = async () => { const items = await listPlugins(); setPlugins(items); };
  useEffect(() => { if (active) void refresh().catch((error) => onActivity(`Plugin list failed: ${String(error)}`)); }, [active]);
  useEffect(() => { setPlan(undefined); setOutput(""); }, [device, destination, useSudo, deleteStale]);
  const install = async (source: string) => { setBusy(true); try { const plugin = await installPlugin(source); await refresh(); setPackagePath(""); onActivity(`Plugin installed: ${plugin.id} ${plugin.version}`); } catch (error) { onActivity(`Plugin install failed: ${String(error)}`); } finally { setBusy(false); } };
  const preview = async () => { if (!device || !sysroot) return; setBusy(true); try { const next = await pluginPreview(sysroot.id, device, sysrootArgs); setPlan(next); setOutput(""); onActivity(`Plugin preflight ready: ${sysroot.id} for ${device}`); } catch (error) { setPlan(undefined); onActivity(`Plugin preflight failed: ${String(error)}`); } finally { setBusy(false); } };
  const execute = async () => { if (!device || !sysroot || !plan) return; setBusy(true); try { const result = await runPlugin(sysroot.id, device, sysrootArgs); setOutput(result.output || result.detail); onActivity(result.detail); } catch (error) { setOutput(String(error)); onActivity(`Plugin execution failed: ${String(error)}`); } finally { setBusy(false); } };
  return <section className="plugins-panel"><header className="plugins-header"><div><strong>Plugins</strong><span>Local, reviewable extension packages for Ferry workflows</span></div><button className="icon-button" title="Refresh installed plugins" onClick={() => void refresh()} disabled={busy}><RefreshCcw size={16} className={busy ? "spin" : ""} /></button></header><div className="plugins-scroll">
    <section className="plugin-section"><h2><PackagePlus size={15} /> Install extensions</h2><p>Packages are installed from a local directory containing <code>plugin.toml</code> and its declared entrypoint. Review package code before installing.</p><div className="plugin-install-row"><input value={packagePath} onChange={(event) => setPackagePath(event.target.value)} placeholder="/path/to/ferry-plugin" /><button title="Install local plugin package" disabled={!packagePath || busy} onClick={() => void install(packagePath)}><FolderPlus size={15} /></button></div>{!sysroot && <button className="operation-button" disabled={busy} onClick={() => void install("sysroot-sync")}><Download size={15} />Install Sysroot Sync</button>}</section>
    <section className="plugin-section"><h2><ShieldCheck size={15} /> Installed packages</h2>{plugins.length ? plugins.map((plugin) => <article className="plugin-card" key={plugin.id}><div><strong>{plugin.name}</strong><span>{plugin.id} · v{plugin.version}</span></div><p>{plugin.description}</p><div className="plugin-tags"><span>{plugin.transport}</span><span>{plugin.risk}</span>{plugin.requires.map((requirement) => <span key={requirement}>needs {requirement}</span>)}</div></article>) : <p className="operation-note">No plugin is installed yet. The built-in Sysroot Sync plugin is ready to install locally.</p>}</section>
    {sysroot && <section className="plugin-section sysroot-section"><h2><Download size={15} /> Sync target sysroot</h2><p>Copies <code>/lib</code>, <code>/usr/lib</code>, and <code>/usr/include</code> from the selected SSH target with rsync. Ferry supplies the profile's user, host, port, key, legacy compatibility, known-hosts, and connection reuse options.</p><label>Local sysroot destination<input value={destination} onChange={(event) => setDestination(event.target.value)} placeholder={`~/ferry-sysroots/${device || "target"}`} /></label><div className="check-grid"><label><input type="checkbox" checked={useSudo} onChange={(event) => setUseSudo(event.target.checked)} />Use sudo for destination ownership</label><label><input type="checkbox" checked={deleteStale} onChange={(event) => setDeleteStale(event.target.checked)} />Delete local files absent on target</label></div>{hasPassword && <div className="plugin-warning"><AlertTriangle size={14} />Desktop plugins use SSH keys only. A saved profile password is never passed to a plugin; install and verify the public key first.</div>}{useSudo && <div className="plugin-warning"><AlertTriangle size={14} />Desktop execution cannot answer a sudo password prompt. Pre-authorize with <code>sudo -v</code> in a terminal, or use a writable user directory.</div>}<button className="operation-button preview" disabled={!device || transport !== "ssh" || busy} onClick={() => void preview()}>{busy ? <LoaderCircle size={15} className="spin" /> : <ShieldCheck size={15} />}{transport !== "ssh" ? "Select an SSH profile" : "Preflight and preview sync"}</button>{plan && <div className="plugin-plan"><strong>{plan.risk}</strong>{plan.steps.map((step) => <p key={step}>{step}</p>)}<code>{plan.command}</code><button className="operation-button danger" disabled={busy} onClick={() => void execute()}><Download size={15} />Run sysroot sync</button></div>}{output && <pre className="plugin-output">{output}</pre>}</section>}
  </div></section>;
}
