import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Download, FolderPlus, LoaderCircle, PackagePlus, RefreshCcw, ShieldCheck } from "lucide-react";
import { installPlugin, listPlugins, pluginPreview, runPlugin } from "./bridge";
import type { PluginPlan, PluginView } from "./types";

interface Props { device: string; transport: string; hasPassword: boolean; active: boolean; onActivity: (message: string) => void; }

const timestamp = () => new Date().toISOString().replace(/[:.]/g, "-");

export function PluginsPanel({ device, transport, hasPassword, active, onActivity }: Props) {
  const [plugins, setPlugins] = useState<PluginView[]>([]); const [destination, setDestination] = useState(""); const [useSudo, setUseSudo] = useState(false); const [deleteStale, setDeleteStale] = useState(false);
  const [treeDestination, setTreeDestination] = useState(""); const [treeBrief, setTreeBrief] = useState(true); const [maxDtNodes, setMaxDtNodes] = useState("512"); const [treeRun, setTreeRun] = useState(0);
  const [packagePath, setPackagePath] = useState(""); const [sysrootPlan, setSysrootPlan] = useState<PluginPlan>(); const [treePlan, setTreePlan] = useState<PluginPlan>(); const [sysrootOutput, setSysrootOutput] = useState(""); const [treeOutput, setTreeOutput] = useState(""); const [busy, setBusy] = useState(false);
  const sysroot = useMemo(() => plugins.find((plugin) => plugin.id === "sysroot-sync"), [plugins]);
  const deviceTree = useMemo(() => plugins.find((plugin) => plugin.id === "device-tree-pull"), [plugins]);
  const sysrootArgs = useMemo(() => ["--dest", destination || `~/ferry-sysroots/${device || "target"}`, ...(useSudo ? [] : ["--no-sudo"]), ...(deleteStale ? ["--delete"] : [])], [deleteStale, destination, device, useSudo]);
  const treeDefault = useMemo(() => `~/ferry-hardware/${device || "target"}-${timestamp()}`, [device, treeRun]);
  const treeArgs = useMemo(() => ["--out", treeDestination || treeDefault, ...(treeBrief ? [] : ["--no-brief"]), ...(maxDtNodes.trim() ? ["--max-dt-nodes", maxDtNodes.trim()] : [])], [maxDtNodes, treeBrief, treeDefault, treeDestination]);
  const refresh = async () => { const items = await listPlugins(); setPlugins(items); };
  useEffect(() => { if (active) void refresh().catch((error) => onActivity(`Plugin list failed: ${String(error)}`)); }, [active]);
  useEffect(() => { setSysrootPlan(undefined); setSysrootOutput(""); }, [device, destination, useSudo, deleteStale]);
  useEffect(() => { setTreePlan(undefined); setTreeOutput(""); }, [device, treeDestination, treeBrief, maxDtNodes]);
  const install = async (source: string) => { setBusy(true); try { const plugin = await installPlugin(source); await refresh(); setPackagePath(""); onActivity(`Plugin installed: ${plugin.id} ${plugin.version}`); } catch (error) { onActivity(`Plugin install failed: ${String(error)}`); } finally { setBusy(false); } };
  const previewSysroot = async () => { if (!device || !sysroot) return; setBusy(true); try { const next = await pluginPreview(sysroot.id, device, sysrootArgs); setSysrootPlan(next); setSysrootOutput(""); onActivity(`Plugin preflight ready: ${sysroot.id} for ${device}`); } catch (error) { setSysrootPlan(undefined); onActivity(`Plugin preflight failed: ${String(error)}`); } finally { setBusy(false); } };
  const executeSysroot = async () => { if (!device || !sysroot || !sysrootPlan) return; setBusy(true); try { const result = await runPlugin(sysroot.id, device, sysrootArgs); setSysrootOutput(result.output || result.detail); onActivity(result.detail); } catch (error) { setSysrootOutput(String(error)); onActivity(`Plugin execution failed: ${String(error)}`); } finally { setBusy(false); } };
  const previewTree = async () => { if (!device || !deviceTree) return; setBusy(true); try { const next = await pluginPreview(deviceTree.id, device, treeArgs); setTreePlan(next); setTreeOutput(""); onActivity(`Plugin preflight ready: ${deviceTree.id} for ${device}`); } catch (error) { setTreePlan(undefined); onActivity(`Plugin preflight failed: ${String(error)}`); } finally { setBusy(false); } };
  const executeTree = async () => { if (!device || !deviceTree || !treePlan) return; setBusy(true); try { const result = await runPlugin(deviceTree.id, device, treeArgs); setTreeOutput(result.output || result.detail); onActivity(result.detail); if (result.ok) { setTreePlan(undefined); setTreeRun((value) => value + 1); } } catch (error) { setTreeOutput(String(error)); onActivity(`Plugin execution failed: ${String(error)}`); } finally { setBusy(false); } };
  const sshPasswordNote = transport === "ssh" && hasPassword && <div className="plugin-warning"><AlertTriangle size={14} />Desktop plugins use SSH keys only. A saved profile password is never passed to a plugin; install and verify the public key first.</div>;
  return <section className="plugins-panel"><header className="plugins-header"><div><strong>Plugins</strong><span>Local, reviewable extension packages for Ferry workflows</span></div><button className="icon-button" title="Refresh installed plugins" onClick={() => void refresh()} disabled={busy}><RefreshCcw size={16} className={busy ? "spin" : ""} /></button></header><div className="plugins-scroll">
    <section className="plugin-section"><h2><PackagePlus size={15} /> Install extensions</h2><p>Packages are installed from a local directory containing <code>plugin.toml</code> and its declared entrypoint. Review package code before installing.</p><div className="plugin-install-row"><input value={packagePath} onChange={(event) => setPackagePath(event.target.value)} placeholder="/path/to/ferry-plugin" /><button title="Install local plugin package" disabled={!packagePath || busy} onClick={() => void install(packagePath)}><FolderPlus size={15} /></button></div>{!sysroot && <button className="operation-button" disabled={busy} onClick={() => void install("sysroot-sync")}><Download size={15} />Install Sysroot Sync</button>}{!deviceTree && <button className="operation-button preview" disabled={busy} onClick={() => void install("device-tree-pull")}><Download size={15} />Install Device Tree Pull</button>}</section>
    <section className="plugin-section"><h2><ShieldCheck size={15} /> Installed packages</h2>{plugins.length ? plugins.map((plugin) => <article className="plugin-card" key={plugin.id}><div><strong>{plugin.name}</strong><span>{plugin.id} · v{plugin.version}</span></div><p>{plugin.description}</p><div className="plugin-tags"><span>{plugin.transport}</span><span>{plugin.risk}</span>{plugin.requires.map((requirement) => <span key={requirement}>needs {requirement}</span>)}</div></article>) : <p className="operation-note">No plugin is installed yet. Sysroot Sync and Device Tree Pull are available as built-ins.</p>}</section>
    {sysroot && <section className="plugin-section sysroot-section"><h2><Download size={15} /> Sync target sysroot</h2><p>Copies <code>/lib</code>, <code>/usr/lib</code>, and <code>/usr/include</code> from the selected SSH target with rsync. Ferry supplies the profile's user, host, port, key, legacy compatibility, known-hosts, and connection reuse options.</p><label>Local sysroot destination<input value={destination} onChange={(event) => setDestination(event.target.value)} placeholder={`~/ferry-sysroots/${device || "target"}`} /></label><div className="check-grid"><label><input type="checkbox" checked={useSudo} onChange={(event) => setUseSudo(event.target.checked)} />Use sudo for destination ownership</label><label><input type="checkbox" checked={deleteStale} onChange={(event) => setDeleteStale(event.target.checked)} />Delete local files absent on target</label></div>{sshPasswordNote}{useSudo && <div className="plugin-warning"><AlertTriangle size={14} />Desktop execution cannot answer a sudo password prompt. Pre-authorize with <code>sudo -v</code> in a terminal, or use a writable user directory.</div>}<button className="operation-button preview" disabled={!device || transport !== "ssh" || busy} onClick={() => void previewSysroot()}>{busy ? <LoaderCircle size={15} className="spin" /> : <ShieldCheck size={15} />}{transport !== "ssh" ? "Select an SSH profile" : "Preflight and preview sync"}</button>{sysrootPlan && <div className="plugin-plan"><strong>{sysrootPlan.risk}</strong>{sysrootPlan.steps.map((step) => <p key={step}>{step}</p>)}<code>{sysrootPlan.command}</code><button className="operation-button danger" disabled={busy} onClick={() => void executeSysroot()}><Download size={15} />Run sysroot sync</button></div>}{sysrootOutput && <pre className="plugin-output">{sysrootOutput}</pre>}</section>}
    {deviceTree && <section className="plugin-section device-tree-section"><h2><Download size={15} /> Pull live device tree</h2><p>Collects a raw <code>device-tree.tar</code> with Ferry's read-only hardware collector. It also saves <code>hardware.json</code> and, unless disabled, a local <code>peripherals.md</code> summary. SSH and authorized ADB profiles are supported.</p><label>Local collection directory<input value={treeDestination} onChange={(event) => setTreeDestination(event.target.value)} placeholder={treeDefault} /></label><label>Decoded DT node limit<input value={maxDtNodes} onChange={(event) => setMaxDtNodes(event.target.value)} inputMode="numeric" placeholder="Leave blank for no limit" /></label><div className="check-grid"><label><input type="checkbox" checked={treeBrief} onChange={(event) => setTreeBrief(event.target.checked)} />Generate local peripheral brief</label></div>{sshPasswordNote}<div className="plugin-warning"><AlertTriangle size={14} />The collection directory must be new or empty. Ferry removes its target temporary directory after the archive is recovered.</div><button className="operation-button preview" disabled={!device || (transport !== "ssh" && transport !== "adb") || busy} onClick={() => void previewTree()}>{busy ? <LoaderCircle size={15} className="spin" /> : <ShieldCheck size={15} />}{transport !== "ssh" && transport !== "adb" ? "Select an SSH or ADB profile" : "Preflight and preview collection"}</button>{treePlan && <div className="plugin-plan"><strong>{treePlan.risk}</strong>{treePlan.steps.map((step) => <p key={step}>{step}</p>)}<code>{treePlan.command}</code><button className="operation-button danger" disabled={busy} onClick={() => void executeTree()}><Download size={15} />Pull device tree</button></div>}{treeOutput && <pre className="plugin-output">{treeOutput}</pre>}</section>}
  </div></section>;
}
