import { useState } from "react";
import { BadgeCheck, LoaderCircle, Radar, Router, ScanSearch, ShieldAlert } from "lucide-react";
import { scanNetwork } from "./bridge";
import type { DeviceForm, ScanHit } from "./types";
import { newDevice } from "./types";

interface Props { onDraft: (form: DeviceForm) => void; onActivity: (message: string) => void; }

export function ScanPanel({ onDraft, onActivity }: Props) {
  const [subnet, setSubnet] = useState(""); const [useMdns, setUseMdns] = useState(true); const [hits, setHits] = useState<ScanHit[]>([]); const [scanning, setScanning] = useState(false);
  const scan = async () => { setScanning(true); try { const found = await scanNetwork(subnet, useMdns); setHits(found); onActivity(`Scan completed: ${found.length} network device(s) found.`); } catch (error) { onActivity(`Scan failed: ${String(error)}`); } finally { setScanning(false); } };
  const draft = (hit: ScanHit) => { const form = newDevice(); form.name = hit.hostname || hit.knownAs || `board-${hit.ip.replaceAll(".", "-")}`; form.host = hit.ip; form.port = hit.open.includes(22) ? 22 : (hit.open.includes(8022) ? 8022 : 22); form.legacy = hit.legacy; onDraft(form); };
  return <section className="scan-panel"><header className="scan-header"><div><strong>Discover Devices</strong><span>mDNS, parallel TCP probes, SSH banner and Ferry fingerprint matching</span></div></header><div className="scan-scroll"><section className="scan-controls"><label>Subnet override<input value={subnet} onChange={(event) => setSubnet(event.target.value)} placeholder="Leave blank to scan local IPv4 /24 networks" /></label><label className="scan-check"><input type="checkbox" checked={useMdns} onChange={(event) => setUseMdns(event.target.checked)} />Query mDNS before port scanning</label><button className="command-button" disabled={scanning} onClick={() => void scan()}>{scanning ? <LoaderCircle size={15} className="spin" /> : <ScanSearch size={15} />}{scanning ? "Scanning network..." : "Scan devices"}</button><p>Scanning is read-only. Selecting a new discovery only creates an unsaved profile draft.</p></section><section className="scan-results">{hits.map((hit) => <article className="scan-hit" key={hit.ip}><div className="scan-hit-title"><Radar size={16} /><strong>{hit.ip}</strong><span>{hit.via}</span>{hit.knownAs && <b><BadgeCheck size={13} />Known as {hit.knownAs}</b>}</div><div className="scan-meta"><span><Router size={13} />{hit.open.map((port) => `:${port}`).join(" ") || "mDNS only"}</span>{hit.hostname && <span>{hit.hostname}</span>}{hit.mac && <span>{hit.mac}</span>}</div>{hit.banner && <pre>{hit.banner}</pre>}{hit.legacy && <div className="legacy-note"><ShieldAlert size={13} />Dropbear/legacy SSH detected; the draft enables legacy algorithms.</div>}<button className="operation-button" disabled={Boolean(hit.knownAs)} onClick={() => draft(hit)}>{hit.knownAs ? "Profile already exists" : "Create profile draft"}</button></article>)}{!scanning && !hits.length && <div className="scan-empty">Run a scan to discover SSH, ADB, telnet, HTTP, mDNS and fingerprint-recognized devices on the reachable network.</div>}</section></div></section>;
}
