import { useState } from "react";
import { BadgeCheck, LoaderCircle, Radar, Router, ScanSearch, ShieldAlert } from "lucide-react";
import { scanNetwork } from "./bridge";
import type { DeviceForm, ScanHit } from "./types";
import { newDevice } from "./types";

interface Props { onDraft: (form: DeviceForm) => void; onActivity: (message: string) => void; }

export function ScanPanel({ onDraft, onActivity }: Props) {
  const [subnet, setSubnet] = useState(""); const [extraPorts, setExtraPorts] = useState(""); const [useMdns, setUseMdns] = useState(true); const [hits, setHits] = useState<ScanHit[]>([]); const [scanning, setScanning] = useState(false);
  const scan = async () => { setScanning(true); try { const found = await scanNetwork(subnet, useMdns, extraPorts); setHits(found); const suffix = extraPorts.trim() ? `; extra ports: ${extraPorts.trim()}` : ""; onActivity(`Scan completed: ${found.length} network device(s) found${suffix}.`); } catch (error) { onActivity(`Scan failed: ${String(error)}`); } finally { setScanning(false); } };
  const draft = (hit: ScanHit) => { const form = newDevice(); form.name = hit.hostname || hit.knownAs || `board-${hit.ip.replaceAll(".", "-")}`; form.transport = hit.transport; if (hit.transport === "ssh") { form.host = hit.ip; form.port = hit.loginPort; form.legacy = hit.legacy; } else { form.adbSerial = `${hit.ip}:${hit.loginPort}`; } onDraft(form); };
  return <section className="scan-panel"><header className="scan-header"><div><strong>Discover Devices</strong><span>Verified SSH banners and authorized network ADB endpoints only</span></div></header><div className="scan-scroll"><section className="scan-controls"><label>Subnet override<input value={subnet} onChange={(event) => setSubnet(event.target.value)} placeholder="Leave blank to scan local IPv4 /24 networks" /></label><label>Extra SSH ports<input value={extraPorts} onChange={(event) => setExtraPorts(event.target.value)} inputMode="numeric" placeholder="For example: 2222, 2200" /></label><label className="scan-check"><input type="checkbox" checked={useMdns} onChange={(event) => setUseMdns(event.target.checked)} />Query mDNS before port scanning</label><button className="command-button" disabled={scanning} onClick={() => void scan()}>{scanning ? <LoaderCircle size={15} className="spin" /> : <ScanSearch size={15} />}{scanning ? "Scanning network..." : "Scan devices"}</button><p>Standard SSH/ADB ports are always checked. Extra ports accept up to 16 comma-separated values and appear only after an SSH protocol banner is verified. Selecting one creates an unsaved profile draft.</p></section><section className="scan-results">{hits.map((hit) => <article className="scan-hit" key={`${hit.transport}-${hit.ip}-${hit.loginPort}`}><div className="scan-hit-title"><Radar size={16} /><strong>{hit.ip}</strong><span>{hit.transport.toUpperCase()} :{hit.loginPort}</span>{hit.knownAs && <b><BadgeCheck size={13} />Known as {hit.knownAs}</b>}</div><div className="scan-meta"><span><Router size={13} />{hit.transport === "ssh" ? `SSH :${hit.loginPort}` : `ADB :${hit.loginPort}`}</span>{hit.hostname && <span>{hit.hostname}</span>}{hit.mac && <span>{hit.mac}</span>}</div>{hit.banner && <pre>{hit.banner}</pre>}{hit.legacy && <div className="legacy-note"><ShieldAlert size={13} />Dropbear/legacy SSH detected; the draft enables legacy algorithms.</div>}<button className="operation-button" disabled={Boolean(hit.knownAs)} onClick={() => draft(hit)}>{hit.knownAs ? "Profile already exists" : `Create ${hit.transport.toUpperCase()} profile`}</button></article>)}{!scanning && !hits.length && <div className="scan-empty">No verified SSH or authorized network ADB endpoint was found on the reachable network.</div>}</section></div></section>;
}
